import os
import json
import uuid
from pathlib import Path
from datetime import date

from unittest.mock import patch

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "clm_backend.settings")
base_dir = Path(__file__).resolve().parent

os.environ.setdefault("R2_BUCKET_NAME", "contract-test-bucket")
os.environ.setdefault("R2_ACCESS_KEY_ID", "test-access")
os.environ.setdefault("R2_SECRET_ACCESS_KEY", "test-secret")
os.environ.setdefault("R2_ENDPOINT_URL", "https://fake-r2.local")

import django

django.setup()

from django.conf import settings  # noqa: E402
from django.contrib.auth import get_user_model  # noqa: E402
from django.core.management import call_command  # noqa: E402
from django.core.files.uploadedfile import SimpleUploadedFile  # noqa: E402
from rest_framework.test import APIClient  # noqa: E402
class FakeS3Client:
    """Minimal fake S3 client for R2 interactions during tests."""

    def __init__(self):
        self._objects = {}

    def put_object(self, Bucket, Key, Body, ContentType=None, Metadata=None):  # noqa: N802
        self._objects[(Bucket, Key)] = {
            "body": Body,
            "content_type": ContentType,
            "metadata": Metadata or {},
        }

    def generate_presigned_url(self, ClientMethod, Params, ExpiresIn):  # noqa: N802
        key = Params.get("Key")
        return f"https://fake-r2.local/{key}?expires={ExpiresIn}"

    def delete_object(self, Bucket, Key):  # noqa: N802
        self._objects.pop((Bucket, Key), None)

    def head_object(self, Bucket, Key):  # noqa: N802
        if (Bucket, Key) not in self._objects:
            raise KeyError(f"Object {Key} missing in bucket {Bucket}")
        return {}


def ensure_database():
    """Ensure migrations have run against the configured database."""
    call_command("migrate", interactive=False, verbosity=0)


def main():
    ensure_database()

    client = APIClient()
    User = get_user_model()

    email = "automation_user@example.com"
    password = "Str0ngP@ssword1!"

    User.objects.filter(email=email).delete()
    user = User.objects.create_user(email=email, password=password)

    results = []

    login_resp = client.post(
        "/api/auth/login/",
        {"email": email, "password": password},
        format="json",
    )
    results.append(
        {
            "action": "login",
            "status_code": login_resp.status_code,
            "payload": login_resp.data,
        }
    )
    if login_resp.status_code != 200:
        raise SystemExit(json.dumps(results, indent=2, default=str))

    token = login_resp.data["access"]
    client.credentials(HTTP_AUTHORIZATION=f"Bearer {token}")

    clause_id = f"CL-{uuid.uuid4().hex[:8].upper()}"
    clause_payload = {
        "clause_id": clause_id,
        "name": "Automation Clause",
        "contract_type": "MSA",
        "content": "Confidentiality obligations for {{counterparty}}.",
        "status": "published",
        "is_mandatory": True,
    }
    clause_resp = client.post("/api/v1/clauses/", clause_payload, format="json")
    results.append(
        {
            "action": "create_clause",
            "status_code": clause_resp.status_code,
            "payload": clause_resp.data,
        }
    )
    if clause_resp.status_code not in (200, 201):
        raise SystemExit(json.dumps(results, indent=2, default=str))

    template_payload = {
        "name": f"Automation Template {uuid.uuid4().hex[:6]}",
        "contract_type": "MSA",
        "description": "Template generated by test harness",
        "status": "published",
        "r2_key": "templates/test.docx",
        "merge_fields": ["counterparty", "value", "start_date", "end_date"],
        "mandatory_clauses": [clause_id],
        "business_rules": {},
    }
    template_resp = client.post(
        "/api/v1/contract-templates/", template_payload, format="json"
    )
    results.append(
        {
            "action": "create_template",
            "status_code": template_resp.status_code,
            "payload": template_resp.data,
        }
    )
    if template_resp.status_code not in (200, 201):
        raise SystemExit(json.dumps(results, indent=2, default=str))

    template_id = template_resp.data["id"]
    structured_inputs = {
        "counterparty": "Acme Corp",
        "value": 250000,
        "start_date": date.today().isoformat(),
        "end_date": date.today().replace(year=date.today().year + 1).isoformat(),
    }
    generate_payload = {
        "template_id": template_id,
        "structured_inputs": structured_inputs,
        "user_instructions": "Generate standard contract",
        "title": f"Automation Contract {uuid.uuid4().hex[:4]}",
        "selected_clauses": [clause_id],
    }
    generate_resp = client.post(
        "/api/v1/contracts/generate/", generate_payload, format="json"
    )
    results.append(
        {
            "action": "generate_contract",
            "status_code": generate_resp.status_code,
            "payload": generate_resp.data,
        }
    )
    if generate_resp.status_code not in (200, 201):
        raise SystemExit(json.dumps(results, indent=2, default=str))

    contract_id = generate_resp.data["contract"]["id"]

    list_resp = client.get("/api/v1/contracts/")
    results.append(
        {
            "action": "list_contracts",
            "status_code": list_resp.status_code,
            "payload": list_resp.data,
        }
    )
    if list_resp.status_code != 200:
        raise SystemExit(json.dumps(results, indent=2, default=str))

    versions_resp = client.get(f"/api/v1/contracts/{contract_id}/versions/")
    results.append(
        {
            "action": "list_versions",
            "status_code": versions_resp.status_code,
            "payload": versions_resp.data,
        }
    )
    if versions_resp.status_code != 200:
        raise SystemExit(json.dumps(results, indent=2, default=str))

    new_version_payload = {
        "selected_clauses": [clause_id],
        "change_summary": "Automation version update",
    }
    new_version_resp = client.post(
        f"/api/v1/contracts/{contract_id}/create-version/",
        new_version_payload,
        format="json",
    )
    results.append(
        {
            "action": "create_version",
            "status_code": new_version_resp.status_code,
            "payload": new_version_resp.data,
        }
    )
    if new_version_resp.status_code not in (200, 201):
        raise SystemExit(json.dumps(results, indent=2, default=str))

    clauses_resp = client.get(
        f"/api/v1/contracts/{contract_id}/versions/1/clauses/"
    )
    results.append(
        {
            "action": "version_clauses",
            "status_code": clauses_resp.status_code,
            "payload": clauses_resp.data,
        }
    )
    if clauses_resp.status_code != 200:
        raise SystemExit(json.dumps(results, indent=2, default=str))

    fake_s3 = FakeS3Client()
    test_file = SimpleUploadedFile(
        "automation.docx",
        b"Fake contract content for upload",
        content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )
    with patch("authentication.r2_service.boto3.client", return_value=fake_s3):
        upload_resp = client.post(
            "/api/v1/upload-document/",
            {"file": test_file, "filename": "automation.docx"},
            format="multipart",
        )
    results.append(
        {
            "action": "upload_document",
            "status_code": upload_resp.status_code,
            "payload": upload_resp.data,
        }
    )
    if upload_resp.status_code not in (200, 201):
        raise SystemExit(json.dumps(results, indent=2, default=str))

    with patch("authentication.r2_service.boto3.client", return_value=fake_s3):
        download_url_resp = client.get(
            f"/api/v1/contracts/{contract_id}/download-url/"
        )
    results.append(
        {
            "action": "contract_download_url",
            "status_code": download_url_resp.status_code,
            "payload": download_url_resp.data,
        }
    )
    if download_url_resp.status_code != 200:
        raise SystemExit(json.dumps(results, indent=2, default=str))

    print(json.dumps(results, indent=2, default=str))


if __name__ == "__main__":
    main()
