# Generated by Django 5.0 on 2026-01-01 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, help_text="Tenant ID for RLS"),
                ),
                ("name", models.CharField(help_text="Rule name", max_length=255)),
                ("description", models.TextField(help_text="Rule description")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("mandatory_clause", "Mandatory Clause"),
                            ("clause_suggestion", "Clause Suggestion"),
                            ("validation", "Validation Rule"),
                            ("restriction", "Restriction Rule"),
                        ],
                        help_text="Type of rule",
                        max_length=50,
                    ),
                ),
                (
                    "contract_types",
                    models.JSONField(
                        default=list,
                        help_text="Applicable contract types (empty = all)",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        help_text='Rule conditions in JSON format: {"contract_value__gte": 10000000, "contract_type": "MSA"}'
                    ),
                ),
                (
                    "action",
                    models.JSONField(
                        help_text='Action to take: {"type": "require_clause", "clause_id": "LIAB-001", "message": "Liability clause required for high-value contracts"}'
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Rule priority (higher = evaluated first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this rule active?"),
                ),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created the rule"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "business_rules",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "rule_type"],
                        name="business_ru_tenant__086025_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="business_ru_is_acti_7041d4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Clause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, help_text="Tenant ID for RLS"),
                ),
                (
                    "clause_id",
                    models.CharField(
                        help_text="Unique clause identifier (e.g., CONF-001)",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(help_text="Clause name", max_length=255)),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Clause version number"),
                ),
                (
                    "contract_type",
                    models.CharField(
                        help_text="Applicable contract type", max_length=100
                    ),
                ),
                ("content", models.TextField(help_text="Clause text content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, help_text="Is this clause mandatory?"
                    ),
                ),
                (
                    "alternatives",
                    models.JSONField(
                        default=list,
                        help_text='Alternative clause IDs with rationale and confidence: [{"clause_id": "CONF-002", "rationale": "Higher value contracts", "confidence": 0.89, "trigger_rules": {"contract_value__gte": 10000000}}]',
                    ),
                ),
                (
                    "tags",
                    models.JSONField(default=list, help_text="Tags for categorization"),
                ),
                (
                    "source_template",
                    models.CharField(
                        blank=True,
                        help_text="Source template name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source_template_version",
                    models.IntegerField(
                        blank=True, help_text="Source template version", null=True
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created the clause"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "clauses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "contract_type"],
                        name="clauses_tenant__4bd4a3_idx",
                    ),
                    models.Index(
                        fields=["clause_id"], name="clauses_clause__4053ee_idx"
                    ),
                ],
                "unique_together": {("tenant_id", "clause_id", "version")},
            },
        ),
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, help_text="Tenant ID for RLS"),
                ),
                ("name", models.CharField(help_text="Template name", max_length=255)),
                (
                    "contract_type",
                    models.CharField(
                        help_text="Type of contract (NDA, MSA, etc.)", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Template description", null=True
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Template version number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "r2_key",
                    models.CharField(
                        help_text="R2 storage key for DOCX template", max_length=500
                    ),
                ),
                (
                    "merge_fields",
                    models.JSONField(
                        default=list, help_text="List of merge field names"
                    ),
                ),
                (
                    "mandatory_clauses",
                    models.JSONField(
                        default=list, help_text="List of mandatory clause IDs"
                    ),
                ),
                (
                    "business_rules",
                    models.JSONField(
                        default=dict, help_text="Contract-specific business rules"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created the template"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "contract_templates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "contract_type"],
                        name="contract_te_tenant__8e3d2f_idx",
                    ),
                    models.Index(
                        fields=["status"], name="contract_te_status_faa3ab_idx"
                    ),
                ],
                "unique_together": {("tenant_id", "name", "version")},
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, help_text="Tenant ID for RLS"),
                ),
                ("title", models.CharField(help_text="Contract title", max_length=255)),
                (
                    "current_version",
                    models.IntegerField(default=1, help_text="Current version number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executed", "Executed"),
                        ],
                        default="draft",
                        help_text="Contract workflow status",
                        max_length=20,
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Explicit approval flag"
                    ),
                ),
                (
                    "approved_by",
                    models.UUIDField(
                        blank=True, help_text="User ID who approved", null=True
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Approval timestamp", null=True
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created the contract"),
                ),
                (
                    "counterparty",
                    models.CharField(
                        blank=True,
                        help_text="Counterparty name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of contract (NDA, MSA, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Contract value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Contract start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Contract end date", null=True
                    ),
                ),
                (
                    "form_inputs",
                    models.JSONField(
                        default=dict, help_text="Structured intake form inputs"
                    ),
                ),
                (
                    "user_instructions",
                    models.TextField(
                        blank=True, help_text="Optional user instructions", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source template used to generate this contract",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="contracts.contracttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField(help_text="Version number")),
                (
                    "r2_key",
                    models.CharField(
                        help_text="R2 storage key for DOCX", max_length=500
                    ),
                ),
                ("template_id", models.UUIDField(help_text="Template ID used")),
                (
                    "template_version",
                    models.IntegerField(help_text="Template version used"),
                ),
                (
                    "change_summary",
                    models.TextField(
                        blank=True, help_text="Summary of changes", null=True
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created this version"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, help_text="SHA-256 hash", max_length=64, null=True
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Parent contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "db_table": "contract_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="ContractClause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "clause_id",
                    models.CharField(help_text="Clause identifier", max_length=100),
                ),
                (
                    "clause_version",
                    models.IntegerField(help_text="Clause version used"),
                ),
                (
                    "clause_name",
                    models.CharField(
                        help_text="Clause name (denormalized)", max_length=255
                    ),
                ),
                (
                    "clause_content",
                    models.TextField(help_text="Clause content (snapshot)"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, help_text="Was this clause mandatory?"
                    ),
                ),
                (
                    "position",
                    models.IntegerField(help_text="Clause position in contract"),
                ),
                (
                    "alternatives_suggested",
                    models.JSONField(
                        default=list, help_text="Alternative clauses suggested"
                    ),
                ),
                (
                    "contract_version",
                    models.ForeignKey(
                        help_text="Contract version this clause belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="contracts.contractversion",
                    ),
                ),
            ],
            options={
                "db_table": "contract_clauses",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if failed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "db_table": "generation_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("submitted", "Submitted for Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executed", "Executed"),
                            ("deleted", "Deleted"),
                            ("version_created", "Version Created"),
                            ("clause_added", "Clause Added"),
                            ("clause_removed", "Clause Removed"),
                            ("clause_updated", "Clause Updated"),
                        ],
                        help_text="Action performed",
                        max_length=20,
                    ),
                ),
                (
                    "performed_by",
                    models.UUIDField(help_text="User ID who performed the action"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment/reason", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional metadata", null=True
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Related contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_logs",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["tenant_id", "status"], name="contracts_tenant__3657e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["tenant_id", "created_at"], name="contracts_tenant__35e3f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractversion",
            index=models.Index(
                fields=["contract", "version_number"],
                name="contract_ve_contrac_a535d5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractversion",
            unique_together={("contract", "version_number")},
        ),
        migrations.AddIndex(
            model_name="contractclause",
            index=models.Index(
                fields=["contract_version", "position"],
                name="contract_cl_contrac_96f5da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contractclause",
            index=models.Index(
                fields=["clause_id"], name="contract_cl_clause__6418cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowlog",
            index=models.Index(
                fields=["contract", "timestamp"], name="workflow_lo_contrac_7c4ca6_idx"
            ),
        ),
    ]
