# Generated by Django 4.2.8 on 2026-01-04 03:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="approval_chain",
            field=models.JSONField(
                default=list, help_text="Sequential approval chain configuration"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="approval_required",
            field=models.BooleanField(
                default=True, help_text="Does this contract require approval?"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="current_approvers",
            field=models.JSONField(
                default=list, help_text="List of user IDs who are current approvers"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="document_r2_key",
            field=models.CharField(
                blank=True,
                help_text="R2 key for uploaded document",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="last_edited_at",
            field=models.DateTimeField(
                blank=True, help_text="Last edit timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="last_edited_by",
            field=models.UUIDField(
                blank=True, help_text="User ID who last edited the contract", null=True
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("executed", "Executed"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Contract workflow status",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ContractEditHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("edited_by", models.UUIDField(help_text="User ID who made the edit")),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changes",
                    models.JSONField(
                        help_text='JSON describing changes: {"field": "title", "old_value": "Old Title", "new_value": "New Title"}'
                    ),
                ),
                (
                    "change_summary",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable summary of changes",
                        null=True,
                    ),
                ),
                (
                    "version_before",
                    models.IntegerField(help_text="Version number before edit"),
                ),
                (
                    "version_after",
                    models.IntegerField(help_text="Version number after edit"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Contract that was edited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_history",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "db_table": "contract_edit_history",
                "ordering": ["-edited_at"],
                "indexes": [
                    models.Index(
                        fields=["contract", "edited_at"],
                        name="contract_ed_contrac_11cd37_idx",
                    ),
                    models.Index(
                        fields=["edited_by"], name="contract_ed_edited__951b44_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(help_text="Contract version being approved"),
                ),
                (
                    "approver",
                    models.UUIDField(help_text="User ID who needs to approve"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Approval status",
                        max_length=20,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0, help_text="Order in approval chain (0 = parallel)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Is this approval mandatory?"
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, help_text="When approver responded", null=True
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Approver comments", null=True
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Contract requiring approval",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "db_table": "contract_approvals",
                "ordering": ["sequence", "requested_at"],
                "indexes": [
                    models.Index(
                        fields=["contract", "status"],
                        name="contract_ap_contrac_b17240_idx",
                    ),
                    models.Index(
                        fields=["approver", "status"],
                        name="contract_ap_approve_69e4fa_idx",
                    ),
                ],
            },
        ),
    ]
