# Generated by Django 5.0 on 2026-01-05 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracts",
            "0002_contract_approval_chain_contract_approval_required_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, help_text="Tenant ID for RLS"),
                ),
                ("user_id", models.UUIDField(help_text="User ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("legal", "Legal Team"),
                            ("sales", "Sales Team"),
                            ("finance", "Finance Team"),
                            ("manager", "Manager"),
                            ("user", "Standard User"),
                        ],
                        help_text="User role",
                        max_length=50,
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text='Specific permissions: ["approve_contracts", "create_templates", "view_audit_logs"]',
                    ),
                ),
                (
                    "assigned_by",
                    models.UUIDField(help_text="User ID who assigned this role"),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Role expiration (null = no expiration)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "user_roles",
                "ordering": ["user_id", "role"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "user_id"],
                        name="user_roles_tenant__174127_idx",
                    ),
                    models.Index(
                        fields=["role", "is_active"], name="user_roles_role_fb4918_idx"
                    ),
                ],
                "unique_together": {("tenant_id", "user_id", "role")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, help_text="Tenant ID for RLS"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Workflow name (e.g., "High Value Contract Approval")',
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Workflow description", null=True
                    ),
                ),
                (
                    "contract_types",
                    models.JSONField(
                        default=list,
                        help_text="Applicable contract types (empty = all)",
                    ),
                ),
                (
                    "trigger_conditions",
                    models.JSONField(
                        default=dict,
                        help_text='Conditions that trigger this workflow: {"contract_value__gte": 100000, "contract_type": "MSA"}',
                    ),
                ),
                (
                    "stages",
                    models.JSONField(
                        default=list,
                        help_text='Workflow stages configuration: [{"stage_name": "Legal Review", "sequence": 1, "approvers": ["role:legal"], "parallel": false, "sla_hours": 48}]',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this workflow active?"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Workflow priority (higher = selected first)",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created this workflow"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflow_definitions",
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "is_active"],
                        name="workflow_de_tenant__84cf45_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="workflow_de_priorit_3b28d0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SLARule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, help_text="Tenant ID for RLS"),
                ),
                ("name", models.CharField(help_text="SLA rule name", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "stage_name",
                    models.CharField(
                        blank=True,
                        help_text="Specific stage (null = applies to all)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("sla_hours", models.IntegerField(help_text="SLA time in hours")),
                (
                    "escalation_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable escalation on breach"
                    ),
                ),
                (
                    "escalation_users",
                    models.JSONField(
                        default=list, help_text="User IDs to notify on escalation"
                    ),
                ),
                (
                    "escalation_message",
                    models.TextField(
                        blank=True, help_text="Custom escalation message", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.UUIDField(help_text="User ID who created this rule"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow_definition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific workflow (null = applies to all)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_rules",
                        to="contracts.workflowdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "sla_rules",
                "ordering": ["sla_hours"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_stage",
                    models.IntegerField(
                        default=0, help_text="Current stage sequence number"
                    ),
                ),
                (
                    "current_stage_name",
                    models.CharField(help_text="Current stage name", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional workflow metadata"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Associated contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_instances",
                        to="contracts.contract",
                    ),
                ),
                (
                    "workflow_definition",
                    models.ForeignKey(
                        help_text="Workflow definition used",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="contracts.workflowdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_instances",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient", models.UUIDField(help_text="User ID of recipient")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("in_app", "In-App"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Notification subject", max_length=255),
                ),
                ("message", models.TextField(help_text="Notification message body")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Priority (higher = sent first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="For in-app notifications", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if failed", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (links, actions, etc.)",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related contract (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="contracts.contract",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related workflow (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="contracts.workflowinstance",
                    ),
                ),
            ],
            options={
                "db_table": "notification_queue",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStageApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage_sequence",
                    models.IntegerField(help_text="Stage sequence number"),
                ),
                (
                    "stage_name",
                    models.CharField(help_text="Stage name", max_length=255),
                ),
                ("approver", models.UUIDField(help_text="User ID of approver")),
                (
                    "approver_role",
                    models.CharField(
                        blank=True,
                        help_text="Approver role (if role-based)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("delegated", "Delegated"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Is this approval mandatory?"
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, help_text="SLA deadline", null=True
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "delegated_to",
                    models.UUIDField(
                        blank=True, help_text="User ID if delegated", null=True
                    ),
                ),
                ("delegation_reason", models.TextField(blank=True, null=True)),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        help_text="Parent workflow instance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_approvals",
                        to="contracts.workflowinstance",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_stage_approvals",
                "ordering": ["stage_sequence", "requested_at"],
            },
        ),
        migrations.CreateModel(
            name="SLABreach",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("breach_time", models.DateTimeField(auto_now_add=True)),
                (
                    "expected_completion",
                    models.DateTimeField(
                        help_text="When it should have been completed"
                    ),
                ),
                (
                    "actual_completion",
                    models.DateTimeField(
                        blank=True, help_text="When actually completed", null=True
                    ),
                ),
                (
                    "breach_duration_hours",
                    models.FloatField(help_text="How many hours overdue"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "escalated",
                    models.BooleanField(
                        default=False, help_text="Has this been escalated?"
                    ),
                ),
                ("escalation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                (
                    "sla_rule",
                    models.ForeignKey(
                        help_text="SLA rule that was breached",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts.slarule",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        help_text="Workflow instance with breach",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_breaches",
                        to="contracts.workflowinstance",
                    ),
                ),
                (
                    "stage_approval",
                    models.ForeignKey(
                        help_text="Specific approval with breach",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_breaches",
                        to="contracts.workflowstageapproval",
                    ),
                ),
            ],
            options={
                "db_table": "sla_breaches",
                "ordering": ["-breach_time"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True, help_text="Tenant ID for RLS"),
                ),
                (
                    "user_id",
                    models.UUIDField(help_text="User who performed the action"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("contract_created", "Contract Created"),
                            ("contract_updated", "Contract Updated"),
                            ("contract_deleted", "Contract Deleted"),
                            ("contract_viewed", "Contract Viewed"),
                            ("contract_exported", "Contract Exported"),
                            ("contract_imported", "Contract Imported"),
                            ("workflow_started", "Workflow Started"),
                            ("workflow_completed", "Workflow Completed"),
                            ("workflow_cancelled", "Workflow Cancelled"),
                            ("approval_requested", "Approval Requested"),
                            ("approval_approved", "Approval Approved"),
                            ("approval_rejected", "Approval Rejected"),
                            ("approval_delegated", "Approval Delegated"),
                            ("template_created", "Template Created"),
                            ("template_updated", "Template Updated"),
                            ("clause_created", "Clause Created"),
                            ("clause_updated", "Clause Updated"),
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("role_assigned", "Role Assigned"),
                            ("settings_changed", "Settings Changed"),
                            ("sla_rule_created", "SLA Rule Created"),
                            ("sla_rule_updated", "SLA Rule Updated"),
                            ("sla_breach", "SLA Breach"),
                            ("sla_escalation", "SLA Escalation"),
                        ],
                        help_text="Action performed",
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Type of resource (contract, template, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(help_text="ID of the affected resource"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="User IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string", null=True
                    ),
                ),
                (
                    "changes",
                    models.JSONField(default=dict, help_text="Details of changes made"),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional context"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related contract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "timestamp"],
                        name="audit_logs_tenant__eb751d_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="audit_logs_user_id_88267f_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_logs_action_474804_idx",
                    ),
                    models.Index(
                        fields=["contract", "timestamp"],
                        name="audit_logs_contrac_5e5de6_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_logs_resourc_bda8a6_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="slarule",
            index=models.Index(
                fields=["tenant_id", "is_active"], name="sla_rules_tenant__9e8096_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slarule",
            index=models.Index(
                fields=["workflow_definition", "stage_name"],
                name="sla_rules_workflo_ab4730_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["contract", "status"], name="workflow_in_contrac_25bb49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["status", "started_at"], name="workflow_in_status_57a7cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationqueue",
            index=models.Index(
                fields=["recipient", "status"], name="notificatio_recipie_31f667_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationqueue",
            index=models.Index(
                fields=["status", "created_at"], name="notificatio_status_ae26fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstageapproval",
            index=models.Index(
                fields=["workflow_instance", "stage_sequence"],
                name="workflow_st_workflo_077eac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstageapproval",
            index=models.Index(
                fields=["approver", "status"], name="workflow_st_approve_a14b96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstageapproval",
            index=models.Index(
                fields=["status", "due_at"], name="workflow_st_status_87d342_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slabreach",
            index=models.Index(
                fields=["status", "breach_time"], name="sla_breache_status_574fe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slabreach",
            index=models.Index(
                fields=["workflow_instance", "status"],
                name="sla_breache_workflo_cc3074_idx",
            ),
        ),
    ]
