# Generated by Django 5.0 on 2026-01-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracts",
            "0003_userrole_workflowdefinition_slarule_workflowinstance_and_more",
        ),
    ]

    operations = []
