# Generated by Django 5.0 on 2026-01-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_add_metadata_description_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="description",
            field=models.TextField(
                blank=True, help_text="Contract description", null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="metadata",
            field=models.JSONField(
                default=dict,
                help_text="AI metadata (embeddings, generation status, etc.)",
            ),
        ),
    ]
