# Generated by Django 5.0 on 2026-02-17 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_rename_template_fi_tenant__925725_idx_tmpl_tenant_updated_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='InhouseSignatureContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent for Signature'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('failed', 'Failed')], db_index=True, default='draft', max_length=50)),
                ('signing_order', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('executed_pdf', models.BinaryField(blank=True, null=True)),
                ('executed_pdf_content_type', models.CharField(default='application/pdf', max_length=100)),
                ('signing_request_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(help_text='Associated CLM contract', on_delete=django.db.models.deletion.CASCADE, related_name='inhouse_signature_contract', to='contracts.contract')),
            ],
            options={
                'db_table': 'inhouse_signature_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InhouseSigner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('recipient_index', models.IntegerField(default=0, help_text='0-based index used for signature placement mapping')),
                ('signing_order', models.IntegerField(default=0, help_text='Order in signing sequence (1-based). 0 for parallel')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('viewed', 'Viewed'), ('in_progress', 'In Progress'), ('signed', 'Signed'), ('declined', 'Declined')], db_index=True, default='invited', max_length=20)),
                ('has_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('signature_png', models.BinaryField(blank=True, null=True)),
                ('signature_mime', models.CharField(default='image/png', max_length=50)),
                ('signed_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_user_agent', models.TextField(blank=True, null=True)),
                ('signed_device_id', models.CharField(blank=True, max_length=128, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inhouse_signature_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='contracts.inhousesignaturecontract')),
            ],
            options={
                'db_table': 'inhouse_signers',
                'ordering': ['signing_order', 'email'],
            },
        ),
        migrations.CreateModel(
            name='InhouseSigningAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('invite_sent', 'Invitation Sent'), ('link_viewed', 'Link Viewed'), ('signing_started', 'Signing Started'), ('signing_completed', 'Signing Completed'), ('signing_declined', 'Signing Declined'), ('status_checked', 'Status Checked'), ('document_downloaded', 'Document Downloaded'), ('error', 'Error')], db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=128, null=True)),
                ('extra', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('inhouse_signature_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='contracts.inhousesignaturecontract')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='contracts.inhousesigner')),
            ],
            options={
                'db_table': 'inhouse_signing_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inhousesignaturecontract',
            index=models.Index(fields=['status'], name='inhouse_sc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inhousesignaturecontract',
            index=models.Index(fields=['contract', 'status'], name='ih_sc_contract_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inhousesigner',
            index=models.Index(fields=['inhouse_signature_contract', 'status'], name='inhouse_signer_sc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inhousesigner',
            index=models.Index(fields=['email'], name='inhouse_signer_email_idx'),
        ),
        migrations.AddIndex(
            model_name='inhousesigner',
            index=models.Index(fields=['access_token'], name='inhouse_signer_token_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inhousesigner',
            unique_together={('inhouse_signature_contract', 'email')},
        ),
        migrations.AddIndex(
            model_name='inhousesigningauditlog',
            index=models.Index(fields=['inhouse_signature_contract', 'created_at'], name='ih_audit_sc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inhousesigningauditlog',
            index=models.Index(fields=['event', 'created_at'], name='ih_audit_event_created_idx'),
        ),
    ]
