# Generated by Django 5.0 on 2026-02-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_inhousesignaturecontract_inhousesigner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhousesignaturecontract',
            name='certificate_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inhousesignaturecontract',
            name='certificate_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inhousesignaturecontract',
            name='certificate_pdf_content_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='inhousesigner',
            name='signature_placement',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='inhousesigningauditlog',
            name='event',
            field=models.CharField(choices=[('invite_sent', 'Invitation Sent'), ('invite_email_sent', 'Invite Email Sent'), ('link_viewed', 'Link Viewed'), ('signing_started', 'Signing Started'), ('signing_completed', 'Signing Completed'), ('certificate_generated', 'Certificate Generated'), ('completion_email_sent', 'Completion Email Sent'), ('signing_declined', 'Signing Declined'), ('status_checked', 'Status Checked'), ('document_downloaded', 'Document Downloaded'), ('error', 'Error')], db_index=True, max_length=50),
        ),
    ]
