# Generated by Django 5.0 on 2026-01-26 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReviewContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("created_by", models.UUIDField(db_index=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, default="", max_length=24)),
                ("size_bytes", models.IntegerField(default=0)),
                ("r2_key", models.CharField(db_index=True, max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=32,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("extracted_text", models.TextField(blank=True, default="")),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("analysis", models.JSONField(blank=True, default=dict)),
                ("review_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "review_contracts",
                "ordering": ["-created_at"],
            },
        ),
    ]
