# Generated by Django 5.0 on 2026-01-26 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClauseLibraryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("key", models.CharField(max_length=200)),
                ("category", models.CharField(db_index=True, max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "default_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "review_clause_library",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "category"],
                        name="review_clau_tenant__e69082_idx",
                    )
                ],
                "unique_together": {("tenant_id", "key")},
            },
        ),
    ]
