# Generated by Django 5.0 on 2026-01-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_alter_user_is_superuser_alter_user_last_login_and_more",
        ),
        ("authentication", "0002_auto_20260103_0514"),
    ]

    operations = []
